development: &defaults
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: real_calendar
  host: localhost
  port: <%= ENV["PGPORT"] || 5432 %>
  username: postgres
  password: postgres
test:
  << : *defaults
  database: real_calendar_test
production:
  << : *defaults
